version: "3.7"
services:
  redis:
    image: redis:5.0.4
    ports:
      - "6379:6379"

  fam100:
    build: .
    depends_on:
      - redis
    volumes:
      - "./qna:/questions"
    environment:
      TELEGRAM_KEY: "${TELEGRAM_KEY}"
      QUESTION_DB_PATH: "questions/test.db"
      REDIS_ADDR: "redis:6379"

